graph TD
    subgraph Inputs 
        direction LR
        %% Input Definitions %%
        InputCSV@{ shape: doc, label: "InputCSV"}
        BaktaDB@{shape: cyl, label; "path baktaDB"}
        Training@{shape: text, label: "path Training file" }
        Genus@{shape: text, label: "val Genus" }
        Species@{shape: text, label: "val Species" }
        Comment@{shape: text, label: "val Comment" }
        OutputDBPath@{shape: text, label: "path OutputDBPath" }
    end

    subgraph "Workflow: DPI"
        direction TB
        %% Processes Definitions %%
        INPUT["`INPUT
            (_R_)
            format validation`"]
        ANNOTATE["`ANNOTATE
            (_Bakta_)
            genome annotation`"]
        PREPARE_NUCDIFF["`PREPARE_NUCDIFF
            (_python_) Parsing 
            longest genome as ref`"]
        RUN_NUCDIFF["`RUN_NUCDIFF
            (_NucDiff via mummer_)
            pairwise comparison 
            classification of differences types`"]
        PREPARE_VCF_ANNOTATOR["`PREPARE_VCF_ANNOTATOR
            (_python_) Parsing`"]
        RUN_VCF_ANNOTATOR["`RUN_VCF_ANNOTATOR
            (_vcf-annotator_)
            annotation of VCF files`"]
        WRANGLING_TO_DB["`WRANGLING_TO_DB
            (_pyton_)
            parsing nucdiff results
            and annotated vcf to dataframes`"]
        MERGE_DBS["`MERGE_DBS
            (_python_)
            merging of all dataframes
            into a single sqlite3 database`"]

        %% Input to process
        InputCSV --> INPUT
        BaktaDB --> ANNOTATE
        Training --> ANNOTATE
        Genus --> ANNOTATE
        Species --> ANNOTATE
        Comment --> WRANGLING_TO_DB
        OutputDBPath --> MERGE_DBS
        
        %% Channels manipulations %% 
        INPUT -. Genome isolates  .-> ANNOTATE
        INPUT -. Isolate pairs .-> PREPARE_NUCDIFF
        PREPARE_NUCDIFF -. ref_query pair (fna) .-> RUN_NUCDIFF
        RUN_NUCDIFF -. ref_query SNPs (vcf) .-> PREPARE_VCF_ANNOTATOR
        PREPARE_VCF_ANNOTATOR -. parsed ref_query and query_ref SNPs (vcf) .-> RUN_VCF_ANNOTATOR
        ANNOTATE -. Genome annotations (gff) .-> RUN_VCF_ANNOTATOR
        RUN_VCF_ANNOTATOR -. ref_query & query_ref annotated SNPs (vcf) .-> WRANGLING_TO_DB
        RUN_NUCDIFF -. ref_query & query_ref differences (gff) + stats .-> WRANGLING_TO_DB
        ANNOTATE -. features, info, sequences (json) .-> WRANGLING_TO_DB
        WRANGLING_TO_DB -. collating parsed dataframes .-> MERGE_DBS
        end

        
        subgraph "Output"
        direction TB
        %% Outputs %%
        %% Need to be defined %% 
        MERGE_DBS -- sqlite3 database --> sqlite3DBDB@{shape: cyl, label; "sqlite3DB"}
        end

%% classDef emptySub color: transparent, stroke: none, fill : transparent; %%
%% class Inputs emptySub; %% 